<?php
namespace App\Database\Migrations;
use CodeIgniter\Database\Migration;
class CreateCommerceTables extends Migration {
 public function up(){ foreach($this->statements() as $sql) $this->db->query($sql); }
 public function down(){ $this->db->disableForeignKeyChecks(); foreach(['payments','order_items','orders','cart_items','addresses','products','categories','otp_logins','users','admins'] as $t) $this->forge->dropTable($t,true); $this->db->enableForeignKeyChecks(); }
 private function statements(): array { return [
"CREATE TABLE admins (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,email VARCHAR(190) NOT NULL UNIQUE,password VARCHAR(255) NOT NULL,created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB",
"CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL UNIQUE,name VARCHAR(100) NULL,phone VARCHAR(20) NULL,created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB",
"CREATE TABLE otp_logins (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,email VARCHAR(190) NOT NULL,otp_code VARCHAR(255) NOT NULL,expires_at DATETIME NOT NULL,is_used TINYINT(1) DEFAULT 0,created_at DATETIME NULL,INDEX(email)) ENGINE=InnoDB",
"CREATE TABLE categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,slug VARCHAR(120) NOT NULL UNIQUE,created_at DATETIME NULL,updated_at DATETIME NULL) ENGINE=InnoDB",
"CREATE TABLE products (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,category_id BIGINT UNSIGNED NOT NULL,name VARCHAR(180) NOT NULL,slug VARCHAR(200) NOT NULL UNIQUE,description TEXT NULL,price DECIMAL(10,2) NOT NULL,sale_price DECIMAL(10,2) NULL,image VARCHAR(255) NULL,hover_image VARCHAR(255) NULL,stock INT DEFAULT 0,status ENUM('active','inactive') DEFAULT 'active',created_at DATETIME NULL,updated_at DATETIME NULL,FOREIGN KEY(category_id) REFERENCES categories(id)) ENGINE=InnoDB",
"CREATE TABLE addresses (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,full_name VARCHAR(100) NOT NULL,phone VARCHAR(20) NOT NULL,line1 VARCHAR(190) NOT NULL,line2 VARCHAR(190) NULL,city VARCHAR(80) NOT NULL,state VARCHAR(80) NOT NULL,pincode VARCHAR(10) NOT NULL,is_default TINYINT(1) DEFAULT 0,created_at DATETIME NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB",
"CREATE TABLE cart_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NULL,session_id VARCHAR(128) NULL,product_id BIGINT UNSIGNED NOT NULL,quantity INT DEFAULT 1,created_at DATETIME NULL,updated_at DATETIME NULL,FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE) ENGINE=InnoDB",
"CREATE TABLE orders (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,address_id BIGINT UNSIGNED NOT NULL,total_amount DECIMAL(10,2) NOT NULL,status ENUM('pending','processing','shipped','delivered','cancelled') DEFAULT 'pending',payment_status ENUM('pending','paid','failed','refunded') DEFAULT 'pending',payment_method VARCHAR(30) DEFAULT 'razorpay',gateway_order_id VARCHAR(100) NULL,created_at DATETIME NULL,updated_at DATETIME NULL,FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(address_id) REFERENCES addresses(id)) ENGINE=InnoDB",
"CREATE TABLE order_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,product_id BIGINT UNSIGNED NOT NULL,product_name VARCHAR(180) NOT NULL,quantity INT NOT NULL,price_at_purchase DECIMAL(10,2) NOT NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE,FOREIGN KEY(product_id) REFERENCES products(id)) ENGINE=InnoDB",
"CREATE TABLE payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,order_id BIGINT UNSIGNED NOT NULL,gateway VARCHAR(30) NOT NULL,transaction_id VARCHAR(120) NULL,amount DECIMAL(10,2) NOT NULL,status ENUM('created','paid','failed','refunded') DEFAULT 'created',raw_response LONGTEXT NULL,notes TEXT NULL,created_at DATETIME NULL,FOREIGN KEY(order_id) REFERENCES orders(id) ON DELETE CASCADE) ENGINE=InnoDB"
 ]; }
}
